# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
stylua = "JohnnyMorganz/StyLua@0.18.0"
selene = "Kampfkarren/selene@0.25.0"
rojo = "rojo-rbx/rojo@7.3.0"
rbxcloud = "Sleitnick/rbxcloud@0.5.0"