[package]
name = "jzou0/javelin-experimental"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

Signal = "sleitnick/signal@2.0.1"
Ripple = "littensy/ripple@0.9.2"
ReactLua = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
Input = "sleitnick/input@2.3.0"
Net = "sleitnick/net@0.2.0"
Charm = "littensy/charm@0.8.1"
CharmSync = "littensy/charm-sync@0.1.1"
ReactCharm = "littensy/react-charm@0.1.1"
Shake = "sleitnick/shake@1.1.0"
TypedRemote = "sleitnick/typed-remote@0.2.0"
#Matter = "matter-ecs/matter@0.8.4"
#Knit = "sleitnick/knit@^1.7"